import type { SearchResultItem } from "./search.types";

export const MOCK_SEARCH_ITEMS: readonly SearchResultItem[] = [
  {
    id: "stop-monas-ambiguous",
    title: "Halte Monas",
    subtitle: "Pilih arah peron perjalanan",
    type: "stop_or_route",
    coordinates: [106.8272, -6.1754],
    source: "gtfs_local",
    aliases: ["monas", "halte monas", "monumen nasional"],
    routes: ["Koridor 1", "Koridor 2"],
    verification: "Data terbatas",
    confidence: "high",
    requiresPlatformChoice: true,
    platforms: [
      {
        id: "stop-monas-plat-1",
        code: "monas-kota",
        label: "Pintu A • Arah Kota / Harmoni",
        coordinates: [106.8271, -6.1753],
      },
      {
        id: "stop-monas-plat-2",
        code: "monas-blok-m",
        label: "Pintu B • Arah Blok M",
        coordinates: [106.8273, -6.1755],
      },
    ],
  },
  {
    id: "stop-blok-m",
    title: "Halte Blok M",
    subtitle: "Kebayoran Baru, Jakarta Selatan",
    type: "stop_or_route",
    coordinates: [106.7981, -6.2444],
    source: "gtfs_local",
    aliases: ["blok m", "blok-m", "halte blok m", "blokm"],
    routes: ["Koridor 1", "10H"],
    walkTimeMinutes: 3,
    walkDistanceMeters: 180,
    verification: "Data terbatas",
    confidence: "high",
  },
  {
    id: "stop-perpusnas",
    title: "Perpustakaan Nasional",
    subtitle: "Non-BRT • Rute 1P, 1R, 2Q",
    type: "stop_or_route",
    coordinates: [106.8271, -6.1804],
    source: "gtfs_local",
    aliases: ["perpusnas", "perpustakaan nasional", "halte perpusnas"],
    routes: ["1P", "1R", "2Q"],
    walkDistanceMeters: 250,
    verification: "Data terbatas",
    confidence: "high",
  },
  {
    id: "poi-monas",
    title: "Monumen Nasional (Monas)",
    subtitle: "Gambir, Jakarta Pusat",
    type: "place_or_address",
    coordinates: [106.8272, -6.1754],
    source: "alias",
    aliases: ["monumen nasional", "monas", "tugu monas"],
    verification: "Data terbatas",
    confidence: "medium",
    placeConversion: {
      stopId: "stop-monas-barat",
      distanceMeters: 350,
      walkingEvidence: "unverified",
    },
  },
  {
    id: "stop-monas-barat",
    title: "Monas Barat",
    subtitle: "Mikrotrans • Rute JAK-10",
    type: "stop_or_route",
    coordinates: [106.8225, -6.1754],
    source: "gtfs_local",
    aliases: ["monas barat", "jak10", "jak 10"],
    routes: ["JAK-10"],
    walkDistanceMeters: 350,
    walkTimeMinutes: 5,
    verification: "Data terbatas",
    confidence: "medium",
  },
  {
    id: "stop-bundaran-hi",
    title: "Halte Bundaran HI",
    subtitle: "Koridor 1, Jakarta Pusat",
    type: "stop_or_route",
    coordinates: [106.823, -6.1955],
    source: "gtfs_local",
    aliases: ["bundaran hi", "halte bundaran indonesia"],
    routes: ["Koridor 1"],
    verification: "Data terbatas",
    confidence: "high",
  },
  {
    id: "stop-gbk",
    title: "Halte GBK",
    subtitle: "Koridor 1, Senayan",
    type: "stop_or_route",
    coordinates: [106.8025, -6.2186],
    source: "gtfs_local",
    aliases: ["gbk", "halte gbk", "gelora bung karno"],
    routes: ["Koridor 1"],
    verification: "Data terbatas",
    confidence: "high",
  },
  {
    id: "poi-grand-indonesia",
    title: "Grand Indonesia",
    subtitle: "Tempat • Jakarta Pusat",
    type: "place_or_address",
    coordinates: [106.8217, -6.1954],
    source: "alias",
    aliases: ["grand indonesia", "gi"],
    verification: "Data terbatas",
    confidence: "medium",
    placeConversion: {
      stopId: "stop-bundaran-hi",
      distanceMeters: 450,
      walkingEvidence: "unverified",
    },
  },
  {
    id: "poi-gbk",
    title: "Gelora Bung Karno",
    subtitle: "Tempat • Senayan",
    type: "place_or_address",
    coordinates: [106.8025, -6.2186],
    source: "alias",
    aliases: ["gbk", "gelora bung karno", "stadion gbk"],
    verification: "Data terbatas",
    confidence: "medium",
    placeConversion: {
      stopId: "stop-gbk",
      distanceMeters: 120,
      walkingEvidence: "unverified",
    },
  },
  {
    id: "stop-senayan-lama",
    title: "Halte Senayan Lama",
    subtitle: "Nama halte perlu dikonfirmasi",
    type: "stop_or_route",
    coordinates: [106.802, -6.214],
    source: "alias",
    aliases: ["senayan lama", "senayanl"],
    routes: ["Koridor 1"],
    verification: "Perlu dicek",
    confidence: "low",
  },
];
